### PR TITLE
Revamp and update README

### PR DESCRIPTION
**Pull request by selectiveduplicate**
[Asana](https://app.asana.com/0/1203280714694408/1206674225685691/f).

### CODE REVIEW

**Comment by praves77** [comment]
@selectiveduplicate and @xinghengwang we have not seen including image for Application-Id in other SDKs. Is this new change moving forward? If yes then we need to make arrow (blue arrow) symmetric - like all horizontals.

**Comment by xinghengwang** [comment]
> @selectiveduplicate and @xinghengwang we have not seen including image for Application-Id in other SDKs. Is this new change moving forward? If yes then we need to make arrow (blue arrow) symmetric - like all horizontals.

I am ok with including images

**Comment by selectiveduplicate** [comment]
@praves77 Yeah that's what we've been doing. I can open PRs for the repo(s) that've been merged and push fixes to the open PRs with the corrected image if you want.

**Comment by praves77** [comment]
Thanks @selectiveduplicate can we update image to have uniform looking blue arrows ? Like they are aligned and always pointing horizontally left to the option (1st and 3rd arrows need to match with 2nd arrow for uniformity)

**Review by praves77 — APPROVED** [review]

**Pull request merged**
